### ISSUE TITLE
UX problem when adding a new question

### ISSUE THREAD

**Issue by ShaharBirzon** [forer11/GroupStudyingApp#110]
when adding a new question to a specific course, the "save" button was visible although no image was uploaded yet:

![before](https://user-images.githubusercontent.com/39333878/85718519-45a77080-b6f7-11ea-8fac-560cabb8bdf5.jpeg)

I think a better UX will be making this button invisible until relevant, so the UI won't be full of irrelevant and unclear buttons. I implemented this for you and now it looks like this:

![after1](https://user-images.githubusercontent.com/39333878/85718554-4cce7e80-b6f7-11ea-8dc0-73368238d24c.jpeg)

and the button is visible only when an image is uploaded:

![after2](https://user-images.githubusercontent.com/39333878/85718578-52c45f80-b6f7-11ea-8f17-4ae65b1b46eb.jpeg)

I also made some small changes in font size and location. Hope you like that!

this is my pr: #109

**Comment by forer11** [comment]
fixed thanks to you
