### ISSUE TITLE
Rating bar ui bug

### ISSUE THREAD

**Issue by edenbrillant** [forer11/GroupStudyingApp#117]
![WhatsApp Image 2020-06-26 at 13 00 07](https://user-images.githubusercontent.com/39674183/85847645-74cde880-b7b0-11ea-81a0-6ce10a9d21db.jpeg)

When trying to rate a question, the rating bar appears underneath the "previous Answer" and "next answer" buttons.

**Comment by forer11** [comment]
fixed
