### ISSUE TITLE
FAB hiding 'delete' icon

### ISSUE THREAD

**Issue by ShaharBirzon** [forer11/GroupStudyingApp#125]
In the course activity, when the recycler view is filling the entire screen, the + fab is hiding the delete button, as shown here:
![course adapter](https://user-images.githubusercontent.com/39333878/85896964-13cf0080-b802-11ea-8719-48d781b48289.jpeg)

Therefore, I suggest maybe remove the 'x' (delete) button entirely (as it makes every item in the recycler view very loaded anyway), and instead, implent a long click listener using `setOnItemLongClickListener` method, and then, when the user long presses an item, a dialog will pop up and ask the user if he is sure to commit the deletion.

**Comment by forer11** [comment]
fixed now button moves
