### ISSUE TITLE
Bug - Filtered results stay the same after orientation change in course activity

### ISSUE THREAD

**Issue by avihai-huji** [forer11/GroupStudyingApp#153]
In CoursePageActivity, when you search for a question, after it filters the question list, if you change the orientation, you can't get back the original unfiltered question list.

Maybe it's related to this bug: https://github.com/forer11/GroupStudyingApp/issues/152.

**Comment by evyatar100** [comment]
I would just disable the orientation change.

**Comment by forer11** [comment]
fixed
