### ISSUE TITLE
suggestion - add a report mechanism

### ISSUE THREAD

**Issue by ShaharBirzon** [forer11/GroupStudyingApp#158]
since the main issue in your app is adding photos of questions and answers and share them with others, I would recommend adding a "report" button and mechanism that will help you get feedback from users about the quality and integrity of your content, and keep track of the content uploaded in general. Because you don't really enforce that the photos uploaded are actually of questions and answers, this will help you keep your content relevant all the time, help find mistakes, and most importantly, keep the goal and functionality of the app as it should be, and prevent offensive/illegal content sharing. 
I implemented this mechanism for you in pr #157 .

**Comment by forer11** [comment]
Thanks for the addition
