### ISSUE TITLE
Remove the delete button 

### ISSUE THREAD

**Issue by evyatar100** [forer11/GroupStudyingApp#160]
I suggest removing the delete button.

Is the questions list, there is a delete button next to each question. Regardless of whether it works or not #108,  Why do we even need this button? It doesn't make any sense to let every user to delete every question (someone can just delete everything). 

What does make sense is to 
1. Add a report mechanism #158 
2. Let users delete their own questions.

Up until (2) is ready, it's better to just remove the option completely.

**Comment by forer11** [comment]
removed thanks!
