### ISSUE TITLE
Bug - answer-rating went down while voting an answer up.

### ISSUE THREAD

**Issue by YonatanKirsh** [forer11/GroupStudyingApp#172]
couldnt find the source for this bug in the code.

**Comment by forer11** [comment]
Can you add a screenshot?

**Comment by YonatanKirsh** [comment]
- rate an answer up
- go to the next answer
- click rating button again. it will 'unrate' and go down one.

this example is from Algorithms-> Test-> 4th answer 
![down-rate example](https://user-images.githubusercontent.com/49614949/86578995-5e304a00-bf85-11ea-8757-a35b50b38600.jpeg)

**Comment by forer11** [comment]
Thank you!! We will look at it

**Comment by mormoshe** [comment]
Thanks, fixed.
