### ISSUE TITLE
Bug - progress bar appears for questions with no solutions

### ISSUE THREAD

**Issue by rutipop** [forer11/GroupStudyingApp#183]
as you can see below- when you enter a screen with a question that has no answers you will see a progress bar
(doesn't happen on screens with questions that have answers)
I can see in the code that you hid the progress bar after a solution was loaded so maybe you forgot to remove it when there are no answers to load?

## https://github.com/rutipop/GroupStudyingApp/commit/7d329178cc7437eae571091bf42622d9f0528a40

![20200705_231242](https://user-images.githubusercontent.com/29456431/86541444-a31c9800-bf15-11ea-8280-96e50cd6d102.gif)

**Comment by forer11** [comment]
pr the fix
