### ISSUE TITLE
bug: button shifted or disappears in activity_send_email

### ISSUE THREAD

**Issue by rutipop** [forer11/GroupStudyingApp#184]
when I tried to add a new course:
the activity didn't fit my screen (Xiaomi Redmi 4) because the "send" button was shifted
also changing the phone orientation made the "send" button disappear (it went down) and there was no option to scroll down

## I made a fix for these issues here if you are interested: https://github.com/rutipop/GroupStudyingApp/commit/ff9cfbe7afb65fe0da06e5cb874f59ef4bf7d5e4

# screenshots of the shifted button:

![k1](https://user-images.githubusercontent.com/29456431/86543432-1ed31080-bf27-11ea-9b7b-4f79dbb121ae.jpg)

![k2](https://user-images.githubusercontent.com/29456431/86543438-22669780-bf27-11ea-9cf2-9a551456922f.jpg)

**Comment by forer11** [comment]
pr it
