### ISSUE TITLE
suggestion: showing the number of voters

### ISSUE THREAD

**Issue by rutipop** [forer11/GroupStudyingApp#185]
first of all - I love your app- great idea and great implementation!

what do you think about adding the number of people who voted for the question? 🤔 
I believe its a pretty important statistic-
that way people will know how popular is the question and if the rank is based on many voters (which means its more reliable)

**Comment by forer11** [comment]
Yeah the idea is that a user can only vote once, we need to implement it on future release, Thanks!!!
