### ISSUE TITLE
Suggestion - add adapter to R.id.rvCourses

### ISSUE THREAD

**Issue by MaxGoldgamer** [forer11/GroupStudyingApp#190]
While making tests for your app, I noticed that R.id.rvCourses does not have an adapter (like CoursesAdapter is used for the list on the main page).
Having an adapter, will make question adding testing possible one step further.

**Comment by mormoshe** [comment]
Hi, 
we have CoursesAdapter for the recyclerView in the MainActivity (for all the courses list), and CoursePageAdapter for the recyclerView in the CoursePageActivity (for all the questions list). Is that what you meant?

**Comment by MaxGoldgamer** [comment]
Walla! you are correct, somehow I missed that.
[My issue is with testing if a certain string exists in the recyclerView. While it works fine with the courses list in the MainActivity, it fails with the questions list in the CoursePageActivity]
I'll check the adapter to see what can be done.
