### ISSUE TITLE
Suggestion - Allow "zooming in" the Question && Answer pics

### ISSUE THREAD

**Issue by Nitay880** [forer11/GroupStudyingApp#224]
As the text can be pretty small , and it's hard to read,
and maybe it's just the emulator that doesn't let me open the picture.

**Comment by forer11** [comment]
Thanks, we will be looking forward to add this feature

**Comment by forer11** [comment]
Added zoom in to question
https://github.com/forer11/GroupStudyingApp/pull/234/commits/12c5defd6448ec2ac536db9864f2c66416425d65
