### ISSUE TITLE
Bug:  Request new course message body gui overflows from the text box

### ISSUE THREAD

**Issue by Nitay880** [forer11/GroupStudyingApp#225]
In case the body of the message is too long the text is seen outside the message box like so 
_illustration_
![image](https://user-images.githubusercontent.com/40713373/87027660-283dd080-c1e6-11ea-8e70-d0d3d89f2388.png)

**How to reproduce:**
-  Click on the "Plus" Sign to request a new course :  _illustration 
![image](https://user-images.githubusercontent.com/40713373/87028417-422be300-c1e7-11ea-9bf1-ff6342d2e7a5.png)

-   Write a long text in the message body

**Possible ways to fix it:**

- limit number of words/chars that are allowded to be inserted as a message body
- enable scrolling when overflow
- change the font-size to just little bit smaller

**Comment by forer11** [comment]
fixed
https://github.com/forer11/GroupStudyingApp/pull/229/commits/3590e8080c51ffb4c2240af75e67513164203854
