### ISSUE TITLE
Bug: New question is not saved if accidentally clicked on the "return" button 

### ISSUE THREAD

**Issue by Nitay880** [forer11/GroupStudyingApp#228]
When adding a new question to the course, student can easily press on the return button by accident,
it's important to keep the context of the last form, even-though it wasn't send yet.
_illustration_
![image](https://user-images.githubusercontent.com/40713373/87034206-237e1a00-c1f0-11ea-85a3-23919857bb5b.png)
accident!!!! 
![image](https://user-images.githubusercontent.com/40713373/87034225-2da01880-c1f0-11ea-9c9c-7332a4a308ab.png)
try to get back
![image](https://user-images.githubusercontent.com/40713373/87034279-46103300-c1f0-11ea-860b-e358aba2d3c2.png)
cant remember my title, and what was the picture and so on.

**way to reproduce** 

is presented in the above photos,

**way of fixing it**

An easy approach can be using "SharedPreferences" to keep the context of the view,
more data is available in here https://developer.android.com/training/basics/data-storage/shared-preferences.html

**Comment by forer11** [comment]
Thanks for the feedback! We did it on purpose as a UX choice
