### ISSUE TITLE
BUG - extra clicks on login causes multiple view reloads

### ISSUE THREAD

**Issue by jherskow** [forer11/GroupStudyingApp#230]
### summary
Inpatient users clicking on login on a slower phone may cause the app to get stuck in a vie load loop/

### steps to reproduce:
when logging in anonymously, click the login button more than once.

### see it
![Screen Recording 2020-07-09 at 19 59 20](https://user-images.githubusercontent.com/18710964/87068997-1d536200-c21f-11ea-9686-ae72b79bf56d.gif)

### Possible solution:
-set a state on the login anonymously button so that it can only trigger it's action  until logging out.

**Comment by forer11** [comment]
Thanks!, fixed here
https://github.com/forer11/GroupStudyingApp/pull/231/commits/64820b86c18bc8b05a74928c1526c99c0a26447f
