### ISSUE TITLE
 "add answer" button overlaps the rating bar

### ISSUE THREAD

**Issue by levYuval1007** [forer11/GroupStudyingApp#85]
![WhatsApp Image 2020-06-21 at 2 07 19 PM](https://user-images.githubusercontent.com/54457246/85223212-da456200-b3c9-11ea-8995-a48136b37ab1.jpeg)

Hi!,
When trying to rate a question, the "add answer" button overlaps the rating bar, by that preventing the user from rating the middle rate.

**Comment by mormoshe** [comment]
Thanks! fixed.
