### ISSUE TITLE
Some improvement suggestions

### ISSUE THREAD

**Issue by edenbrillant** [forer11/GroupStudyingApp#97]
- when adding a question to some curse, you can add different questions with the same title which could be
confusing for the user as he searches through the questions. It might be helpful to prevent this by prevention or
adding a numbering of the questions.
-when writing a title for a question, one can write "%^&*+". Adding a validation of user input in the code
can prevent this and make the titles readable.
- for now i see that it's possible to upload only one solution to a question. Some questions may have more than
one correct answer, so allowing to upload multiple answers can be very helpful for the purpose of this app.
-when uploading an answer for a question, if one wanted to change the solution he can't delete it and can only
delete the entire question. Adding an edit solution button can help.

**Comment by forer11** [comment]
1. We thought as it per course and the questions are in a photo format it wouldn't matter, but we will look into this matter.
2 Good point!
