### ISSUE TITLE
Bug: After adding an answer, pressing 'Show solution' doesn't work.

### ISSUE THREAD

**Issue by evyatar100** [forer11/GroupStudyingApp#99]
Ho to reproduce:

1. Add an answer to a question that has no answers.
2. Press 'Show solution' (immediately, don't leave the question page).
3. A toast prints 'No answer yet'.

I think that a user the uploaded an answer, would like to see how does his answer looks like on the app.

**Comment by forer11** [comment]
fixed thanks to you!
